# Generated by Django 3.2.23 on 2024-02-06 09:28

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, help_text='Tên', max_length=250, null=True)),
                ('desc', models.TextField(blank=True, help_text='Mô tả', max_length=2000, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Số tiền', max_digits=19, null=True)),
                ('is_paid', models.BooleanField(blank=True, default=True, help_text='Đã thanh toán', null=True)),
                ('is_confirm', models.BooleanField(blank=True, default=True, help_text='Được xác nhận', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_Type',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, help_text='Tên', max_length=250, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm cập nhật')),
            ],
        ),
    ]
