# Generated by Django 3.2.23 on 2024-02-06 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('money_Mng', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_type',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='money_mng_transaction_type_created_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='transaction_type',
            name='updated_by',
            field=models.ForeignKey(help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='money_mng_transaction_type_updated_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='borrower',
            field=models.ForeignKey(editable=False, help_text='Người vay', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='money_mng_transaction_borrower', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='money_mng_transaction_created_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='lender',
            field=models.ForeignKey(editable=False, help_text='Người cho vay', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='money_mng_transaction_lender', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='money_mng_transaction_type', to='money_Mng.transaction_type'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_by',
            field=models.ForeignKey(help_text='Người cập nhật', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='money_mng_transaction_updated_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
